### ISSUE TITLE
image swap getting confused somtimes

### ISSUE THREAD

**Issue by idoed** [idoed/TurnsApp#13]
https://github.com/idoed/TurnsApp/blob/00c74403d340b279d5faf773eb664ea5285309a6/app/src/main/java/app/calcounterapplication/com/turnsapp/Fragments/GameBoard.java#L140
i have AsyncTask to poll 1 player from the Queue and Adding the Loosing player to the End of it..
i used singletone to get and set the Left Pic PLayer and the right 1.
i tried to set the iamge in the Post Execute (cant do it in do in background couse background thread cant touch the UI) but i didnt succes to i puted it after my Async task Execute with Thread sleep of 500 mS
somtimes its getting mixed and not the right picture shown. see if you got other solution please :)

**Comment by idoed** [comment]
Solved

**Comment by nirdev** [comment]
If you change issue's status to solved don't forget to push your changes instantly
